CREATE DATABASE regTest;
CREATE TABLE `regTest`.`reg` (
    `ID` VARCHAR(255) NOT NULL , 
    `First_name` VARCHAR(255) NOT NULL , 
    `Last_name` VARCHAR(255) NOT NULL , 
    `Email` VARCHAR(255) NOT NULL , 
    `Password` VARCHAR(255) NOT NULL , 
    PRIMARY KEY (`ID`(255))); 
CREATE USER '3ToneAdmin'@'%' IDENTIFIED WITH caching_sha2_password BY '1111';
GRANT USAGE ON *.* TO '3ToneAdmin'@'%';
ALTER USER '3ToneAdmin'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `regTest`.* TO '3ToneAdmin'@'%'; 